### ISSUE TITLE
Images for README

### ISSUE THREAD

**Issue by clairew** [clairew/PageSummary#1]
<img width="1093" alt="step_1" src="https://cloud.githubusercontent.com/assets/9344258/14197231/0a1ac6b4-f79a-11e5-9eb0-59fdbc25b690.png">
<img width="328" alt="step 2" src="https://cloud.githubusercontent.com/assets/9344258/14197196/c854070e-f799-11e5-8778-2255594cba1d.png">
<img width="375" alt="step 3" src="https://cloud.githubusercontent.com/assets/9344258/14197197/ca7e6772-f799-11e5-87ac-16b4d3eabd05.png">
<img width="443" alt="step 4" src="https://cloud.githubusercontent.com/assets/9344258/14197202/cf012460-f799-11e5-9546-e569302597d3.png">
<img width="580" alt="step 5" src="https://cloud.githubusercontent.com/assets/9344258/14197247/44af07c2-f79a-11e5-9e5d-71df96199338.png">
<img width="854" alt="step 6" src="https://cloud.githubusercontent.com/assets/9344258/14197258/5ac37ebc-f79a-11e5-866b-7656e3d3bf47.png">
<img width="809" alt="step 7" src="https://cloud.githubusercontent.com/assets/9344258/14197263/62f5f9de-f79a-11e5-937f-ee99287e9a9d.png">
<img width="531" alt="step 8" src="https://cloud.githubusercontent.com/assets/9344258/14197264/66bc4456-f79a-11e5-8bb3-def41d511117.png">
<img width="863" alt="step 9" src="https://cloud.githubusercontent.com/assets/9344258/14197265/6a5205d8-f79a-11e5-9fb4-3435bc8aaefe.png">
<img width="978" alt="step 10" src="https://cloud.githubusercontent.com/assets/9344258/14197266/70da921c-f79a-11e5-9bed-8ca1f6aba584.png">
<img width="1026" alt="step 11" src="https://cloud.githubusercontent.com/assets/9344258/14197269/74c466a0-f79a-11e5-9859-7341ce18a80f.png">
<img width="303" alt="step 12" src="https://cloud.githubusercontent.com/assets/9344258/14197271/77d86a12-f79a-11e5-9e5c-47be8c7daedb.png">
<img width="371" alt="step 13" src="https://cloud.githubusercontent.com/assets/9344258/14197273/7b56e754-f79a-11e5-8438-3f78d91b1588.png">

**Comment by FreddieV4** [comment]
I think you can close this now, Claire :)
